# Generated by Django 4.1.3 on 2022-11-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply',
            new_name='comment',
        ),
    ]
